### ISSUE TITLE
Why is partials omitted?

### ISSUE THREAD

**Issue by furzeface** [cartridge/cartridge-static-html#2]
# Project version:

**v1.0.0**
## Issue type:
- [x] Documentation needed 

---

I know it says in the README [here](https://github.com/cartridge/cartridge-static-html/commit/20d0004aeba860a704c33c152e18d879c8bf8710#diff-04c6e90faac2675aa89e2176d2eec7d8R29) about `_partials` being omitted, but why is it? It took me a while to work out that it was done on purpose when I set up a new project via the cli tool.

**Comment by jtuds** [comment]
This omission breaks the Gulp task for me. Only adding the _partials folder, and the header.hbs and footer.hbs files fixes it. Either the folders/files should be added or the Gulp task should be able to run without it I think?

**Comment by furzeface** [comment]
Yes this is what I was thinking @jtuds - also this means that we can incorporate the [meta data from our HTML snippets](https://github.com/code-computerlove/HTML-Snippets/tree/master/meta-data) repository. 

This caught me out when using Cartridge because I’d forgotten some of the basic meta data for the `<head>`.

**Comment by mmacartney10** [comment]
This issue looks like it has already been resolved
